version: '1'

services:
  react-app:
    image: node:22
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install && npm run dev"
    stdin_open: true
    tty: true

  fastapi-backend:
    image: python:3.12
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    command: >
      sh -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 5000 --reload"
